### ISSUE TITLE
Demon Hunter 

### ISSUE THREAD

**Issue by AlifIzwan** [WodNet-Gaming/Tracker#4]
- Missing skills from the reward of the quest / bug quest 
- Cannot teleport to another map

**Comment by WodNet-Gaming** [comment]
please make link what skill you want report
Please Follow report format

**Comment by AlifIzwan** [comment]
Describe the issue you're having:
1.Kayn Sunfury Quests
Explain how you expect it work:
1.Can complete all the quest
Steps to reproduce the problem:
1. Their Numbers Are Legion
2. Fel Secrets
3. Stop the Bombardment
4. Orders for Your Captains
5. Vengeance Will Be Mine
6. Cry Havoc and Let Slip the Illidari

Links to Wowhead, YouTube, etc:
-
![untitled](https://cloud.githubusercontent.com/assets/25533370/22602806/b6a8fea4-ea7f-11e6-96d0-aab5df1c5cf1.png)


Don't forget to add LABEL for all issue

**Comment by AlifIzwan** [comment]
Describe the issue you're having:
1. Izal Whitemoon (Illidari Flight Master)
2. Ride to the Fel Hammer (Portal)
Explain how you expect it work:
1. Can be use or stuck here in this map

Links to Wowhead, YouTube, etc:

![untitled](https://cloud.githubusercontent.com/assets/25533370/22603175/3fd40588-ea81-11e6-9590-1fb662f8e7c7.png)
